### ISSUE TITLE
Package build is broken for newer versions of pip

### ISSUE THREAD

**Issue by dusktreader** [dusktreader/sphinx-view#30]
```
/venv:praetorian/ $ sphinx-view --package --config=docs/conf.py .
.
[2018-05-03 09:59:26,224] DEBUG in server: Registering route
[2018-05-03 09:59:26,225] DEBUG in server: configuring livereload server
[2018-05-03 09:59:26,225] DEBUG in server: Setting up the builder
[2018-05-03 09:59:26,225] DEBUG in builder: Creating virtualenv for package
[2018-05-03 09:59:26,234] DEBUG in builder: Using pip to install target package to virtualenv
Traceback (most recent call last):
  File "/home/tbeck/.virtualenvs/praetorian/bin/sphinx-view", line 76, in <module>
    (server, builder) = create_server(**config)
  File "/home/tbeck/.virtualenvs/praetorian/lib/python3.6/site-packages/sview/server.py", line 43, in create_server
    builder = Builder(logger=app.logger, **config)
  File "/home/tbeck/.virtualenvs/praetorian/lib/python3.6/site-packages/sview/builder.py", line 32, in __init__
    self.setup_venv()
  File "/home/tbeck/.virtualenvs/praetorian/lib/python3.6/site-packages/sview/builder.py", line 45, in setup_venv
    pip.main(['install', self.target])
AttributeError: module 'pip' has no attribute 'main'
```

**Comment by dusktreader** [comment]
resolved by pr #31
